server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  #断言配置也可以在config中进行配置-下面是在yml中进行配置，相对简单
  #访问地址静态
#  cloud:
#    gateway:
#      routes:
#        - id: payment_routes #路由的ID，没有固定的规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/** #断言，路径相匹配的进行路由
#
#        - id: payment_routes2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**
  #配置访问动态路由
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务进行路由
      routes:
        - id: payment_routes #路由的ID，没有固定的规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_routes2
          uri: lb://cloud-payment-service
          #过滤器可以在这里配置，多用自定义过滤器建立类
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头上加一对请求，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由，访问接口路径地址
            #- After=2022-06-20T15:35:29.191+08:00[Asia/Shanghai] #在哪个时间之后才能进行访问
            #- Before=2022-06-20T15:35:29.191+08:00[Asia/Shanghai] #在哪个时间之前才能进行访问
            #- Between=2022-06-20T15:35:29.191+08:00[Asia/Shanghai]，2022-06-20T15:35:29.191+08:00[Asia/Shanghai] #在哪个时间之间才能进行访问
            #- Cookie=username,zzyy #前面是cookie要带key  后面是key要符合的正则表达式
            #- Header=X-Request-Id, \d+ #一个是属性名称，一个是正则表达式  正则表达式和属性匹配则执行
            #- Host=**.xxx.springcloud #接收一组参数一组匹配的域名列表，这个模板是一个ant分隔的模板，用.号作为分隔符
            #- Method=GET #请求的方式方法，那种请求方式才可以请求
            #- Query=username, \d+ #要有参数username,并且值还要是整数才能路由
eureka:
  instance:
    hostname: cloud-gatewat-service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true

