server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进eureka的服务名称
  cloud:
    config:
      server:
        git:
          uri: http://github.com/zkf1273928/springcloud.git #GitHub上面的放配置文件的git仓库名称
          username: zkf1273928721@163.com
          password: Wohuizai99
      #搜索目录
      search-paths:
        - springcloud
    #读取分支
    label: main

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka